import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#9FC63B',
  },
  logContainer: {
    alignContent: 'center',
    flex: 1,
    backgroundColor: '#23272A',
    padding: 40,
    justifyContent: 'center',
  },
  container:{
    paddingTop: 20,
    alignContent: 'center',
    flex: 1,
    backgroundColor: '#23272A',
    justifyContent: 'center',
  },
  container2:{
    height: '100%',
    paddingTop: 50,
    alignContent: 'center',
    backgroundColor: '#23272A',
  },
  text: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: 'Verdana',
  },
  secText: {
    color: '#868686',
    fontSize: 12,
    fontFamily: 'Verdana',
  },
  secContainer:{
    marginTop:10,
    marginBottom:10,
  },
  button: {
    alignContent: 'center',
    width: '50%',
    borderWidth: 2,
    borderColor: '#9FC63B',
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 15,
    alignSelf: 'center',
  },
  buttonLogin:{
    alignContent: 'center',
    width: '50%',
    backgroundColor: '#9FC63B',
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 15,
    alignSelf: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  input: {
    borderBottomWidth: 1,
    borderBottomColor: '#FFFFFF',
    color: '#868686',
    fontSize: 14,
    marginVertical: 8,
    paddingVertical: 6,
  },
  inputLogin: {
    borderRadius: 8,
    paddingHorizontal: 12,
    color: '#868686',
    fontSize: 14,
    marginVertical: 8,
    paddingVertical: 12,
    backgroundColor: '#323639',
},
  imageBackground: {
    height: '50%',
    width: '100%',
    resizeMode: 'cover',
  },
  nickB:{
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Verdana',
  },
  nick:{
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: 'Verdana',
  },
    profileImage: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 3,
      borderColor: '#9FC63B',
      marginRight: 10,
      resizeMode: 'cover',
      aspectRatio:1,
    },
    postImage: {
      width: '100vf',
      height: 400,
    },
    likeContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 10,
      marginLeft: 5,
    },
    likeText: {
      color: '#868686',
      fontFamily: 'Verdana',  
    },
    logo:{
      width: '100%',
      height: '10%',
      marginTop: 0,
      marginBottom: 10,
      alignSelf: 'center',

    },
    postText:{
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 5,
      marginRight: 5,
      width:'90%',
    },
    postText2:{
      marginTop: 5,
      marginBottom: 10,
      marginLeft: 20,
      marginRight: 20,
      width:'90%',
      flex:1,
    },
    card:{
      padding:0,
      marginVertical: 1,
      borderRadius: 10,
      flexDirection: 'column',
    },
    userContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 0,
      zIndex: 1,
      bottom: -60,
      marginLeft:10,
    },
    userContainer2: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      marginLeft:10,
    },
    userTextContainer:{
      flexDirection: 'column',
      alignItems: 'flex-start',
      marginLeft: 10,
    },
    scrollViewContainer: {
      paddingVertical: 40,
      flexGrow: 1,
      backgroundColor: '#23272A',
    },
    commentButton: {
      position: 'absolute',
      bottom: 20,
      right: 20,
      backgroundColor: '#9FC63B',
      padding: 15,
      borderRadius: 30,
      elevation: 5,
      zIndex: 10000,
    },
    commentsContainer: {
      marginTop: 10,
      padding: 10,
    },
    modalBackground: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    commentForm: {
      width: '80%',
      height: 400,
      backgroundColor: '#23272A',
      borderWidth: 2,
      borderColor: '#9fc63b',
      borderRadius: 10,
      padding: 20,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#9FC63B',
      fontFamily: 'Vedrana',
      marginTop: 40,
      marginBottom: 20,
    },
    commentInput: {
      height: 200,
      backgroundColor: '#323639',
      borderRadius: 5,
      marginBottom: 20,
      padding: 10,
      textAlignVertical: 'top',
    },
    titleInput: {
      backgroundColor: '#323639',
      borderRadius: 5,
      marginBottom: 20,
      padding: 10,
      textAlignVertical: 'top',
    },
    formButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 5,
    },
    formButton: {
      alignContent: 'center',
      width: '50%',
      padding: 10,
      borderRadius: 8,
      alignItems: 'center',
      marginVertical: 15,
      alignSelf: 'center',
    },
    submitButton: {
      borderWidth: 2,
      borderColor: '#9FC63B',
    },
    buttonText2: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    commentContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 15,
    },
    commentUserContainer: {
      flexDirection: 'column',
    },
    commentUserPFP: {
      flexDirection: 'row',
      padding: 10,
      alignItems: 'center',
      marginRight: 10,
    },
    commentUserImage: {
      width: 50,
      height: 50,
      borderRadius: 30,
      borderWidth: 3,
      borderColor: '#9FC63B',
      marginRight: 10,
      resizeMode: 'cover',
      aspectRatio:1,
    },
    commentUserNick: {
      color: '#FFFFFF',
      fontSize: 15,
      fontFamily: 'Verdana',
    },
    commentText: {
      padding: 10,
      flex: 1,
    },
    buttonImage:{
      width: '100%',
      height: 150,
      resizeMode: 'cover',
      aspectRatio:1,
    },
    titleCentered:{
      fontSize: 30,
      fontWeight: 'bold',
      color: '#9FC63B',
      fontFamily: 'Vedrana',
      marginTop: 100,
      marginBottom: 40,
      alignSelf: 'center',
    }
});
